plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.focusblack.wallos'
    compileSdk 36

    defaultConfig {
        applicationId "com.focusblack.wallos"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    sourceSets {
        main.res.srcDirs = ['src/main/res']
        main.res.exclude '**/ic_launcher.png'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.0.21"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1"

    // AndroidX Core
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.fragment:fragment-ktx:1.8.9'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.10.0'

    // UI
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'

    // WorkManager
    implementation 'androidx.work:work-runtime-ktx:2.9.0'

    // Play Billing
    implementation 'com.android.billingclient:billing-ktx:7.1.1'
}
